## traefik.yml

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: web-secure
          scheme: https
  web-secure:
    address: :443


api:
  dashboard: true
  insecure: true

providers:
  file:
    filename: /etc/traefik/traefik_dynamic.yml
    watch: true
